### ISSUE TITLE
add member name to readme

### ISSUE THREAD

**Issue by woranit** [woranit/Wonder#1]
it can be either real name or nickname @warunyupa

**Comment by warunyupa** [comment]
I'm already add my name

**Comment by warunyupa** [comment]
Hippo, Please add your name.

**Comment by nalin-sue** [comment]
Hippo name Added

**Comment by nalin-sue** [comment]
Punya, Please add your name @Punnarak

**Comment by woranit** [comment]
Ok!

**Comment by Punnarak** [comment]
Pun name added
